// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC12kCZpE4nRkNiXV4PIkhwjHMjrjIRWyo',
    appId: '1:577583959631:web:ecade5a9bb3b9c06a7a43a',
    messagingSenderId: '577583959631',
    projectId: 'velora-99ed0',
    authDomain: 'velora-99ed0.firebaseapp.com',
    storageBucket: 'velora-99ed0.firebasestorage.app',
    measurementId: 'G-YQ3TMXYST3',
    databaseURL: "https://velora-99ed0-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkHc8-kWeufj9-1kuxOBVRGwpjj3gSSRs',
    appId: '1:577583959631:android:586167d624b6c315a7a43a',
    messagingSenderId: '577583959631',
    projectId: 'velora-99ed0',
    storageBucket: 'velora-99ed0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE4lsUd-Iom8IDH4M7wlkVWtikgTZC-nw',
    appId: '1:577583959631:ios:8b4a7f4434ed2f95a7a43a',
    messagingSenderId: '577583959631',
    projectId: 'velora-99ed0',
    storageBucket: 'velora-99ed0.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE4lsUd-Iom8IDH4M7wlkVWtikgTZC-nw',
    appId: '1:577583959631:ios:8b4a7f4434ed2f95a7a43a',
    messagingSenderId: '577583959631',
    projectId: 'velora-99ed0',
    storageBucket: 'velora-99ed0.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC12kCZpE4nRkNiXV4PIkhwjHMjrjIRWyo',
    appId: '1:577583959631:web:5ed319d2fd36ee2aa7a43a',
    messagingSenderId: '577583959631',
    projectId: 'velora-99ed0',
    authDomain: 'velora-99ed0.firebaseapp.com',
    storageBucket: 'velora-99ed0.firebasestorage.app',
    measurementId: 'G-QY2S8T59L4',
  );
}
